<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Calculator.Shortcuts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="CalculatorShortcuts.json" LogicalName="Calculator.Shortcuts.CalculatorShortcuts.json" />
  </ItemGroup>

</Project>
